export const ROULETTE_OPTIONS = [
  { color: 'green', value: '0' },
  { color: 'red', value: '32' },
  { color: 'black', value: '15' },
  { color: 'red', value: '19' },
  { color: 'black', value: '4' },
  { color: 'red', value: '21' },
  { color: 'black', value: '2' },
  { color: 'red', value: '25' },
  { color: 'black', value: '17' },
  { color: 'red', value: '34' },
  { color: 'black', value: '6' },
  { color: 'red', value: '27' },
  { color: 'black', value: '13' },
  { color: 'red', value: '36' },
  { color: 'black', value: '11' },
  { color: 'red', value: '30' },
  { color: 'black', value: '8' },
  { color: 'red', value: '23' },
  { color: 'black', value: '10' },
  { color: 'red', value: '5' },
  { color: 'black', value: '24' },
  { color: 'red', value: '16' },
  { color: 'black', value: '33' },
  { color: 'red', value: '1' },
  { color: 'black', value: '20' },
  { color: 'red', value: '14' },
  { color: 'black', value: '31' },
  { color: 'red', value: '9' },
  { color: 'black', value: '22' },
  { color: 'red', value: '18' },
  { color: 'black', value: '29' },
  { color: 'red', value: '7' },
  { color: 'black', value: '28' },
  { color: 'red', value: '12' },
  { color: 'black', value: '35' },
  { color: 'red', value: '3' },
  { color: 'black', value: '26' }
];

export const API_URL = "https://dev-games-backend.advbet.com/v1/ab-roulette";
